version: "3" 
services:
  nginx:
      ports:
        - "3000:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development 
      - MONGO_USER=maikltim
      - MONGO_PASSWORD=mypasssword
      - SESSSION_SECRET=secrert
    command: npm run dev 
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=maikltim
      - MONGO_INITDB_ROOT_PASSWORD=mypasssword 

  
    